create schema flight;
CREATE TABLE flight.distances (airports INTEGER, ORIGIN CHAR(3), DEST CHAR(3), DISTANCE FLOAT);
\copy flight.distances FROM '/Users/<>/systemds/distances_dataset_postgres.csv' WITH (FORMAT CSV, NULL '');

CREATE TABLE flight.schedule (flight INTEGER, OP_CARRIER CHAR(2), CRS_DEP_HOUR FLOAT, CRS_DEP_MIN FLOAT, CRS_ARR_HOUR FLOAT, CRS_ARR_MIN FLOAT, airports INTEGER);
\copy flight.schedule FROM '/Users/<>/systemds/schedule_dataset_postgres.csv' WITH (FORMAT CSV, NULL '');

CREATE TABLE flight.flights (DEP_DELAY FLOAT, TAXI_OUT FLOAT, TAXI_IN FLOAT, ARR_DELAY FLOAT, DIVERTED INTEGER, ACTUAL_ELAPSED_TIME FLOAT, AIR_TIME FLOAT, DEP_TIME_HOUR FLOAT, DEP_TIME_MIN FLOAT, 
WHEELS_OFF_HOUR FLOAT, WHEELS_OFF_MIN FLOAT, WHEELS_ON_HOUR FLOAT, WHEELS_ON_MIN FLOAT, ARR_TIME_HOUR FLOAT, ARR_TIME_MIN FLOAT, MONTH_SIN FLOAT, MONTH_COS FLOAT, DAY_SIN FLOAT, DAY_COS FLOAT, WEEKDAY_SIN 
FLOAT, WEEKDAY_COS FLOAT, EXTRA_DAY_ARR INTEGER, EXTRA_DAY_DEP INTEGER, flight INTEGER);
\copy flight.flights FROM '/Users/<>/systemds/airline_dataset_postgres.csv' WITH (FORMAT CSV, NULL '');

